steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'discord-bot'
    - '--source'
    - '.'
    - '--region'
    - 'asia-northeast1'
    - '--no-allow-unauthenticated'
    - '--min-instances=1'
    - '--update-secrets=DISCORD_BOT_TOKEN=discord-bot-token:latest'
    - '--update-secrets=GEMINI_API_KEY=gemini-api-key:latest'
    - '--update-secrets=DISCORD_CLIENT_ID=discord-client-id:latest'
    - '--set-env-vars=REMINDER_ENABLED=true'